name: Roomby.API.Shared-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - main

variables:
- name: buildConfiguration
  value: 'Release'
- name: projectPath
  value: '**/openapi-to-terraform.Main.csproj'
- name: testProjectPath
  value: '**/openapi-to-terraform.[Tt]ests/*.csproj'

stages:
- stage: 'Build'
  displayName: 'Build the tool'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'windows-2019'

    steps:
    - task: NuGetToolInstaller@0
      displayName: 'Use NuGet 5.7'
      inputs:
        versionSpec: 5.7
    
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.13.0'
        
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 5.x'
      inputs:
        version: 5.x
    
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: '$(projectPath)'
    
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: '$(projectPath)'
        arguments: '--configuration $(buildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: test
        projects: '$(testProjectPath)'
        arguments: '--configuration $(buildConfiguration)'
    
    # - task: DotNetCoreCLI@2
    #   displayName: 'dotnet publish'
    #   inputs:
    #     command: publish
    #     publishWebProjects: false
    #     projects: '$(projectPath)'
    #     arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    - task: DotNetCoreCLI@2
      inputs: 
        command: 'pack'
        outputDir: '$(Build.ArtifactStagingDirectory)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'push'
        searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;'
        feedPublish: 'openapi-to-terraform'
