name: openapi-to-terraform-$(Date:yyyyMMdd)$(Rev:.r)
trigger: none

variables:
- name: buildConfiguration
  value: 'Release'
- name: projectPath
  value: '**/openapi-to-terraform.Main.csproj'
- name: testProjectPath
  value: '**/openapi-to-terraform.[Tt]ests/*.csproj'

stages:
- stage: 'Push'
  displayName: 'Push to artifacts feed'
  jobs: 
  - job: 'Push'
    displayName: 'Push job'
    pool:
      vmImage: 'windows-2019'

    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: 'openapi-to-terraform'
        pipeline: 6
        runVersion: 'latest'
        artifact: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: NuGetAuthenticate@0
      displayName: 'Nuget Authenticate'

    - task: DotNetCoreCLI@2
      displayName: "dotnet push"
      inputs:
        command: 'push'
        packagesToPush: '$(System.ArtifactsDirectory)\drop\*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '8c518764-12c4-49f9-be20-50b7f4793712'


    # - script: dotnet nuget push --skip-duplicate --source "tesselatedsky" --api-key az *.nupkg
    #   workingDirectory: $(System.ArtifactsDirectory)
    #   displayName: 'Push package to artifacts feed'
